version: '3.9'

services:
  backend:
    build:
      context: ./book
    ports:
      - "5000:80"
    networks:
      - cookbook

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - cookbook
    depends_on:
      - backend

networks:
  cookbook: